### ISSUE TITLE
Úprava

### ISSUE THREAD

**Issue by Marthinius** [skyjet18/plugin.video.antiktv#3]
Zdravím,

Pro jakou verzi kodi je určen tento doplněk ? Zkoušel jsem Leila, matrix a píše mi to chyba verze python...
Bylo by možné upravit tento doplněk, aby ukládal klíč do určité složky a až při změně klíče se tento nový klíč vygeneroval ?

**Comment by skyjet18** [comment]
To nie je doplnok pre Kodi ale pre archivCZSK https://github.com/mx3L/archivczsk - to je plugin do linuxových sat. prijímačov založených na enigma2. Toto čo je tu sa dá použiť ako inšpirácia pre kodi doplnok, no priamo to fungovať nebude. Ja kodi nepoužívam, preto úpravu robiť nebudem.

**Comment by Marthinius** [comment]
Dobrý den,

děkuji Vám za Vaši rychlou odpověď. Nechci Vás zdržovat, ale mám ještě
jednu otázku.
Jako zákazník mám možnost přehrát programy přes webové rozhraní, díky čemuž
jsem mohl získat adresy tv kanálů.
Bohužel je to dosti nekomfortní.

Jde mi pouze o to, jestli by se dal upravit python skript tak, abych zadal
přihlašovací údaje a stáhl se jen klíč pro dekédování kanálů.
O nic víc mi nejde, ani epg, seznam stanic atd...jen tato jednoduchá f-kce.

Tedy zadat přihlašovací údaje a přes api získat klíč k dekódóvání videa.

Stačilo by tedy z již Vámi uveřejněného "python" skriptu vymazat nepotřebné
věci.
Zkouším to již několik dní, ale neúspěšně.

st 27. 4. 2022 v 16:35 odesílatel skyjet18 ***@***.***>
napsal:
